server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GustaAndrad/ead-config-server-repo
          default-label: main
          username: GustaAndrad
          password: '*****************************'
ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceRegistry
    password: 'ead123'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
    enable: true
  instance:
    hostname: localhost


